# Generated by Django 4.0.2 on 2022-04-19 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerTable',
            fields=[
                ('ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChaoCai',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('num', models.IntegerField()),
                ('price', models.FloatField(primary_key=True, serialize=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canteenapp.dinnertable')),
            ],
        ),
    ]
