# Generated by Django 4.0.2 on 2022-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0002_alter_chaocai_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaocai',
            name='table',
        ),
        migrations.AddField(
            model_name='chaocai',
            name='table',
            field=models.ManyToManyField(to='canteenapp.DinnerTable'),
        ),
    ]
