# Generated by Django 4.0.2 on 2022-04-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0003_remove_chaocai_table_chaocai_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnertable',
            name='a1',
            field=models.CharField(default=0, max_length=10, verbose_name='米饭（1.1元/碗）'),
        ),
        migrations.AddField(
            model_name='dinnertable',
            name='a2',
            field=models.CharField(default=0, max_length=10, verbose_name='炒白菜（3.4元/份）'),
        ),
        migrations.AddField(
            model_name='dinnertable',
            name='a3',
            field=models.CharField(default=0, max_length=10, verbose_name='红烧猪蹄（18元/只）'),
        ),
        migrations.AddField(
            model_name='dinnertable',
            name='a4',
            field=models.CharField(default=0, max_length=10, verbose_name='可乐（3.3元/瓶）'),
        ),
        migrations.DeleteModel(
            name='ChaoCai',
        ),
    ]
